### ISSUE TITLE
Correction orthographique

### ISSUE THREAD

**Issue by edodo7** [dannywillems/master-thesis#1]
Le mot "sûreté" n'est pas bien écrit aux pages :  3, 4, 6, 29, 35, 38 39 .

**Comment by edodo7** [comment]
@dannywillems

**Comment by dannywillems** [comment]
@edodo7 Merci. Cependant, « sureté » est aussi autorisé depuis 1990 (les accents circonflexes peuvent être supprimés dans beaucoup de cas).
Mais je ne suis pas cohérent car parfois je le laisse.

**Comment by edodo7** [comment]
@dannywillems  Tu m'apprends quelque chose.

**Comment by dannywillems** [comment]
@edodo7 Fixed.
